resources:
  repositories:
    - repository: templates
      type: git
      name: Packages/azure.pipelines

trigger:
  tags: 
    include:
    - 'release/v*'
    - 'v*'

pool: 'Unity Pipelines'

jobs:
- template: /tasks/node/publish-npm-package.1.yml